#!/usr/bin/env bash
set -euo pipefail

# setup_mariadb.sh
# Generates MariaDB credentials, writes .env.mariadb and starts the docker-compose-MariaDB.yml stack.
# It also writes the generated credentials into logs/mariadb-credentials.log for the end user to find.

OUT_ENV_FILE=".env.mariadb"
LOG_DIR="logs"
LOG_FILE="$LOG_DIR/mariadb-credentials.log"
COMPOSE_FILE="docker-compose-MariaDB.yml"

mkdir -p "$LOG_DIR"

# Generate strong random password
MARIADB_ROOT_PASSWORD=$(openssl rand -base64 18)
MARIADB_DATABASE="fadb"
MARIADB_USER="fadb"
MARIADB_PASSWORD=$(openssl rand -base64 18)

cat > "$OUT_ENV_FILE" <<EOF
MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
MARIADB_DATABASE=${MARIADB_DATABASE}
MARIADB_USER=${MARIADB_USER}
MARIADB_PASSWORD=${MARIADB_PASSWORD}
EOF

# Write the credentials into logs for the end user to find
cat > "$LOG_FILE" <<EOF
MariaDB credentials generated by setup_mariadb.sh
------------------------------------------------
Please keep these credentials secure. They are printed here so you can find them if you need them.

MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
MARIADB_DATABASE=${MARIADB_DATABASE}
MARIADB_USER=${MARIADB_USER}
MARIADB_PASSWORD=${MARIADB_PASSWORD}

The .env file written is: ${OUT_ENV_FILE}
To start the stack run: docker compose --env-file ${OUT_ENV_FILE} -f ${COMPOSE_FILE} up --build -d
EOF

echo "Wrote ${OUT_ENV_FILE} and ${LOG_FILE}" 

echo "Starting MariaDB + Traefik + server stack using ${COMPOSE_FILE} (this may take a minute)..."

docker compose --env-file "$OUT_ENV_FILE" -f "$COMPOSE_FILE" up --build -d

# Wait for MariaDB to be ready
echo "Waiting for MariaDB to become available..."

MAX_WAIT=60
COUNT=0
until docker exec fadb-mariadb mysqladmin --silent --wait=1 -u root -p"${MARIADB_ROOT_PASSWORD}" ping >/dev/null 2>&1; do
  sleep 1
  COUNT=$((COUNT+1))
  if [ "$COUNT" -ge "$MAX_WAIT" ]; then
    echo "MariaDB did not become ready within ${MAX_WAIT}s. Check logs with: docker compose -f ${COMPOSE_FILE} logs mariadb"
    exit 1
  fi
done

echo "MariaDB is ready. Credentials have been written to ${LOG_FILE}"

echo "Setup complete. You can find credentials in ${LOG_FILE} or ${OUT_ENV_FILE}."
